/**
 * declere types
 */
export const Types = {
    HEALTH: "HEALTH",
    LOGIN: "LOGIN",
    IS_LOGIN_LOADING: "IS_LOGIN_LOADING",
    GET_USERS: "GET_USERS",
    USER_PARAMS: "USER_PARAMS",
    CREATE_USER: "CREATE_USER",
    GET_USER_ROLES: "GET_USER_ROLES",
    ON_OPEN_ALERT_DIALOG: "ON_OPEN_ALERT_DIALOG",
    ON_CLOSE_ALERT_DIALOG: "ON_CLOSE_ALERT_DIALOG",
    ON_SET_LOADER: "ON_SET_LOADER",
    ON_SORT_FIELD: "ON_SORT_FIELD",
    DELETE_USER: "DELETE_USER",
    RESTORE_USER: "RESTORE_USER",
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
    CATEGORY_PARAMS: "CATEGORY_PARAMS",
    CREATE_CATEGORY: "CREATE_CATEGORY",
    DELETE_CATEGORY: "DELETE_CATEGORY",
    UPDATE_CATEGORY: "UPDATE_CATEGORY",
    RESET_PASSWORD: "RESET_PASSWORD",
    GET_ALL_QUESTIONS: "GET_ALL_QUESTIONS",
}