/**
 * declere types
 */
export const Types = {
    HEALTH: "HEALTH",
    LOGIN: "LOGIN",
    IS_LOGIN_LOADING: "IS_LOGIN_LOADING",
    GET_USERS: "GET_USERS",
    CREATE_USER: "CREATE_USER",
    GET_USER_ROLES: "GET_USER_ROLES",
    ON_OPEN_ALERT_DIALOG: "ON_OPEN_ALERT_DIALOG",
    ON_CLOSE_ALERT_DIALOG: "ON_CLOSE_ALERT_DIALOG",
    ON_SET_LOADER: "ON_SET_LOADER",
    ON_PAGE_CHANGE: "ON_PAGE_CHANGE",
    DELETE_USER: "DELETE_USER",
    RESTORE_USER: "RESTORE_USER",
    GET_ALL_CATEGORIES: "GET_ALL_CATEGORIES",
    CREATE_CATEGORY: "CREATE_CATEGORY",
    
}